package org.jordi.solsona.todolistapplication.service;

import org.jordi.solsona.todolistapplication.api.dto.CreateTodoListRequest;
import org.jordi.solsona.todolistapplication.api.dto.UpdateTodoListRequest;
import org.jordi.solsona.todolistapplication.commons.mappers.TodoListMapper;
import org.jordi.solsona.todolistapplication.domain.model.TodoListStatus;
import org.jordi.solsona.todolistapplication.domain.repository.TodoListSpecifications;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.jordi.solsona.todolistapplication.commons.exceptions.ListNotFoundException;
import org.jordi.solsona.todolistapplication.domain.model.TodoList;
import org.jordi.solsona.todolistapplication.domain.repository.TodoListRepository;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.UUID;

@Service
public class TodoListService {

    private final TodoListRepository listRepo;
    private final TodoListMapper mapper;

    @Autowired
    public TodoListService(TodoListRepository listRepo, TodoListMapper mapper) {
        this.listRepo = listRepo;
        this.mapper = mapper;
    }

    /**
     * Creates a new list
     * @param request the {@link CreateTodoListRequest} to be created
     * @return the created {@link TodoList}
     */
    public TodoList createTodoList(CreateTodoListRequest request) {

        //For a distributed system, the id would ideally be generated by the client as sent as part of the request. Since there is no client for this
        //exercise, I am generating the on the server side to simplify the execution, and not have to manually generate new uuid for each request sent
        UUID id = UUID.randomUUID();

        TodoList todoListEntity = this.mapper.toEntity(request);
        todoListEntity.setId(id);
        return this.listRepo.save(todoListEntity);
    }

    /**
     * Get a list by its id.
     * @param id the list id
     * @return the {@link TodoList} with the parameter id.
     */
    public TodoList getTodoListById(UUID id) {
        return this.listRepo.findById(id).orElseThrow(() -> new ListNotFoundException(id));
    }

    /**
     * @param status
     * @param dueTime
     * @param pageable
     * @return all the {@link TodoList} matching the criteria.
     */
    public Page<TodoList> list(TodoListStatus status, Instant dueTime, Pageable pageable) {

        Specification<TodoList> specification = Specification
                .where(TodoListSpecifications.hasStatus(status)).and(TodoListSpecifications.dueBefore(dueTime));

        return this.listRepo.findAll(specification, pageable);
    }

    /**
     *
     * @param id
     */
    public void delete(UUID id) {
        try {
            this.listRepo.deleteById(id);
        } catch (IllegalArgumentException e) {
            throw new ListNotFoundException(id);
        }
    }

    /**
     * Updates an existing list with the values sent in the request.
     * @param id the Id of the {@link TodoList} to update.
     * @param request the request payload containing the new values.
     * @return the updated {@link TodoList}
     */
    public TodoList update(UUID id, UpdateTodoListRequest request) {

        TodoList toBeUpdated = getTodoListById(id);
        toBeUpdated.setName(request.name());
        toBeUpdated.setDescription(request.description());
        toBeUpdated.setDueDate(request.dueDate());
        toBeUpdated.setStatus(request.status());

        return this.listRepo.save(toBeUpdated);
    }
}
